# Generated by Django 5.2.7 on 2026-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
