# Generated by Django 5.2.7 on 2026-08-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_customer_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="document_number",
            field=models.CharField(default="44023757", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="document_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (80, "CUIT"),
                    (86, "CUIL"),
                    (87, "CDI"),
                    (89, "LE"),
                    (90, "LC"),
                    (96, "DNI"),
                    (94, "Pasaporte"),
                    (91, "CI Extranjera"),
                    (0, "CI Policía Federal"),
                    (30, "Certificado de Migración"),
                ],
                default=96,
            ),
            preserve_default=False,
        ),
    ]
