# Generated by Django 5.2.7 on 2026-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_customer_document_number_customer_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="document_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (80, "CUIT"),
                    (86, "CUIL"),
                    (87, "CDI"),
                    (89, "LE"),
                    (90, "LC"),
                    (96, "DNI"),
                    (94, "Pasaporte"),
                    (91, "CI Extranjera"),
                    (0, "CI Policía Federal"),
                    (30, "Certificado de Migración"),
                ],
                default=96,
            ),
        ),
    ]
