# Generated by Django 5.2.7 on 2026-09-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_customer_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="customers/"),
        ),
    ]
