# Generated by Django 5.2.7 on 2026-09-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_customer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True
            ),
        ),
    ]
