# Generated by Django 5.2.7 on 2026-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
