# Generated by Django 5.2.7 on 2026-07-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pto_vta", models.PositiveIntegerField(verbose_name="Punto de venta")),
                (
                    "cbte_tipo",
                    models.PositiveIntegerField(verbose_name="Tipo de comprobante"),
                ),
                (
                    "cbte_nro",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Numbero de comprobante"
                    ),
                ),
                ("imp_neto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("imp_iva", models.DecimalField(decimal_places=2, max_digits=12)),
                ("imp_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cae", models.CharField(blank=True, max_length=14)),
                ("cae_vencimientos", models.CharField(blank=True, max_length=8)),
                ("afip_response", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
