# Generated by Django 5.2.7 on 2026-07-12 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["order", "status"], name="billing_inv_order_i_51aad7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cbte_nro__isnull", False)),
                fields=("pto_vta", "cbte_tipo", "cbte_nro"),
                name="unique_comprobante_afip",
            ),
        ),
    ]
