# Generated by Django 5.2.7 on 2026-07-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_invoice_status"),
        ("orders", "0003_alter_orderitem_unit_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSequenceLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_of_sale",
                    models.PositiveIntegerField(verbose_name="Point of Sale"),
                ),
                (
                    "invoice_type",
                    models.PositiveIntegerField(verbose_name="Invoice Type"),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="unique_comprobante_afip",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="cae_vencimientos",
            new_name="cae_expiration_date",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="imp_neto",
            new_name="net_amount",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="imp_total",
            new_name="total_amount",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="imp_iva",
            new_name="vat_amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="cbte_nro",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="cbte_tipo",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="pto_vta",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Invoice Number"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.PositiveIntegerField(default=1, verbose_name="Invoice Type"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="point_of_sale",
            field=models.PositiveIntegerField(default=1, verbose_name="Point of Sale"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invoice_number__isnull", False)),
                fields=("point_of_sale", "invoice_type", "invoice_number"),
                name="unique_afip_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoicesequencelock",
            constraint=models.UniqueConstraint(
                fields=("point_of_sale", "invoice_type"),
                name="unique_invoice_sequence_lock",
            ),
        ),
    ]
