# Generated by Django 5.2.7 on 2026-09-14 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_invoicesequencelock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
