# Generated by Django 5.2.7 on 2025-12-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
