# Generated by Django 5.2.7 on 2025-12-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued')], default='draft', max_length=20),
        ),
    ]
