# Generated by Django 5.2.7 on 2026-05-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
