# Generated by Django 5.2.7 on 2026-05-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
