# Generated by Django 5.2.7 on 2026-06-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
