# Generated by Django 5.2.7 on 2026-07-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
