// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthLoginCreateData, AuthLoginCreateResponses, AuthLogoutCreateData, AuthLogoutCreateResponses, AuthPasswordChangeCreateData, AuthPasswordChangeCreateResponses, AuthPasswordResetConfirmCreateData, AuthPasswordResetConfirmCreateResponses, AuthPasswordResetCreateData, AuthPasswordResetCreateResponses, AuthUserPartialUpdateData, AuthUserPartialUpdateResponses, AuthUserRetrieveData, AuthUserRetrieveResponses, AuthUserUpdateData, AuthUserUpdateResponses, BrandsCreateData, BrandsCreateResponses, BrandsDestroyData, BrandsDestroyResponses, BrandsListAllData, BrandsListAllResponses, BrandsListData, BrandsListResponses, BrandsPartialUpdateData, BrandsPartialUpdateResponses, BrandsRetrieveData, BrandsRetrieveResponses, BrandsUpdateData, BrandsUpdateResponses, CategoriesCreateData, CategoriesCreateResponses, CategoriesDestroyData, CategoriesDestroyResponses, CategoriesListAllData, CategoriesListAllResponses, CategoriesListData, CategoriesListResponses, CategoriesPartialUpdateData, CategoriesPartialUpdateResponses, CategoriesRetrieveData, CategoriesRetrieveResponses, CategoriesUpdateData, CategoriesUpdateResponses, ProductsCreateData, ProductsCreateResponses, ProductsDestroyData, ProductsDestroyResponses, ProductsDetectAndAssignBrandCreateData, ProductsDetectAndAssignBrandCreateResponses, ProductsGenerateSkuCreateData, ProductsGenerateSkuCreateResponses, ProductsListData, ProductsListResponses, ProductsPartialUpdateData, ProductsPartialUpdateResponses, ProductsRetrieveData, ProductsRetrieveResponses, ProductsUpdateData, ProductsUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Check the credentials and return the REST Token
 * if the credentials are valid and authenticated.
 * Calls Django Auth login method to register User ID
 * in Django session framework
 *
 * Accept the following POST parameters: username, password
 * Return the REST Framework Token Object's key.
 */
export const authLoginCreate = <ThrowOnError extends boolean = false>(options: Options<AuthLoginCreateData, ThrowOnError>): RequestResult<AuthLoginCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthLoginCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/login/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Calls Django logout method and delete the Token object
 * assigned to the current User object.
 *
 * Accepts/Returns nothing.
 */
export const authLogoutCreate = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutCreateData, ThrowOnError>): RequestResult<AuthLogoutCreateResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthLogoutCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/logout/',
    ...options
});

/**
 * Calls Django Auth SetPasswordForm save method.
 *
 * Accepts the following POST parameters: new_password1, new_password2
 * Returns the success/fail message.
 */
export const authPasswordChangeCreate = <ThrowOnError extends boolean = false>(options: Options<AuthPasswordChangeCreateData, ThrowOnError>): RequestResult<AuthPasswordChangeCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthPasswordChangeCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/password/change/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Calls Django Auth PasswordResetForm save method.
 *
 * Accepts the following POST parameters: email
 * Returns the success/fail message.
 */
export const authPasswordResetCreate = <ThrowOnError extends boolean = false>(options: Options<AuthPasswordResetCreateData, ThrowOnError>): RequestResult<AuthPasswordResetCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthPasswordResetCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/password/reset/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Password reset e-mail link is confirmed, therefore
 * this resets the user's password.
 *
 * Accepts the following POST parameters: token, uid,
 * new_password1, new_password2
 * Returns the success/fail message.
 */
export const authPasswordResetConfirmCreate = <ThrowOnError extends boolean = false>(options: Options<AuthPasswordResetConfirmCreateData, ThrowOnError>): RequestResult<AuthPasswordResetConfirmCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthPasswordResetConfirmCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/password/reset/confirm/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reads and updates UserModel fields
 * Accepts GET, PUT, PATCH methods.
 *
 * Default accepted fields: username, first_name, last_name
 * Default display fields: pk, username, email, first_name, last_name
 * Read-only fields: pk, email
 *
 * Returns UserModel fields.
 */
export const authUserRetrieve = <ThrowOnError extends boolean = false>(options?: Options<AuthUserRetrieveData, ThrowOnError>): RequestResult<AuthUserRetrieveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AuthUserRetrieveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/user/',
    ...options
});

/**
 * Reads and updates UserModel fields
 * Accepts GET, PUT, PATCH methods.
 *
 * Default accepted fields: username, first_name, last_name
 * Default display fields: pk, username, email, first_name, last_name
 * Read-only fields: pk, email
 *
 * Returns UserModel fields.
 */
export const authUserPartialUpdate = <ThrowOnError extends boolean = false>(options?: Options<AuthUserPartialUpdateData, ThrowOnError>): RequestResult<AuthUserPartialUpdateResponses, unknown, ThrowOnError> => (options?.client ?? client).patch<AuthUserPartialUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Reads and updates UserModel fields
 * Accepts GET, PUT, PATCH methods.
 *
 * Default accepted fields: username, first_name, last_name
 * Default display fields: pk, username, email, first_name, last_name
 * Read-only fields: pk, email
 *
 * Returns UserModel fields.
 */
export const authUserUpdate = <ThrowOnError extends boolean = false>(options: Options<AuthUserUpdateData, ThrowOnError>): RequestResult<AuthUserUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).put<AuthUserUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/auth/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const brandsList = <ThrowOnError extends boolean = false>(options?: Options<BrandsListData, ThrowOnError>): RequestResult<BrandsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<BrandsListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/',
    ...options
});

export const brandsCreate = <ThrowOnError extends boolean = false>(options: Options<BrandsCreateData, ThrowOnError>): RequestResult<BrandsCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<BrandsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const brandsDestroy = <ThrowOnError extends boolean = false>(options: Options<BrandsDestroyData, ThrowOnError>): RequestResult<BrandsDestroyResponses, unknown, ThrowOnError> => (options.client ?? client).delete<BrandsDestroyResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/{slug}/',
    ...options
});

export const brandsRetrieve = <ThrowOnError extends boolean = false>(options: Options<BrandsRetrieveData, ThrowOnError>): RequestResult<BrandsRetrieveResponses, unknown, ThrowOnError> => (options.client ?? client).get<BrandsRetrieveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/{slug}/',
    ...options
});

export const brandsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<BrandsPartialUpdateData, ThrowOnError>): RequestResult<BrandsPartialUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).patch<BrandsPartialUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/{slug}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const brandsUpdate = <ThrowOnError extends boolean = false>(options: Options<BrandsUpdateData, ThrowOnError>): RequestResult<BrandsUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).put<BrandsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/{slug}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const brandsListAll = <ThrowOnError extends boolean = false>(options?: Options<BrandsListAllData, ThrowOnError>): RequestResult<BrandsListAllResponses, unknown, ThrowOnError> => (options?.client ?? client).get<BrandsListAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/brands/all/',
    ...options
});

export const categoriesList = <ThrowOnError extends boolean = false>(options?: Options<CategoriesListData, ThrowOnError>): RequestResult<CategoriesListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CategoriesListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/',
    ...options
});

export const categoriesCreate = <ThrowOnError extends boolean = false>(options: Options<CategoriesCreateData, ThrowOnError>): RequestResult<CategoriesCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<CategoriesCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const categoriesDestroy = <ThrowOnError extends boolean = false>(options: Options<CategoriesDestroyData, ThrowOnError>): RequestResult<CategoriesDestroyResponses, unknown, ThrowOnError> => (options.client ?? client).delete<CategoriesDestroyResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/{slug}/',
    ...options
});

export const categoriesRetrieve = <ThrowOnError extends boolean = false>(options: Options<CategoriesRetrieveData, ThrowOnError>): RequestResult<CategoriesRetrieveResponses, unknown, ThrowOnError> => (options.client ?? client).get<CategoriesRetrieveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/{slug}/',
    ...options
});

export const categoriesPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<CategoriesPartialUpdateData, ThrowOnError>): RequestResult<CategoriesPartialUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).patch<CategoriesPartialUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/{slug}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const categoriesUpdate = <ThrowOnError extends boolean = false>(options: Options<CategoriesUpdateData, ThrowOnError>): RequestResult<CategoriesUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).put<CategoriesUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/{slug}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const categoriesListAll = <ThrowOnError extends boolean = false>(options?: Options<CategoriesListAllData, ThrowOnError>): RequestResult<CategoriesListAllResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CategoriesListAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/categories/all/',
    ...options
});

export const productsList = <ThrowOnError extends boolean = false>(options?: Options<ProductsListData, ThrowOnError>): RequestResult<ProductsListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ProductsListResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/',
    ...options
});

export const productsCreate = <ThrowOnError extends boolean = false>(options: Options<ProductsCreateData, ThrowOnError>): RequestResult<ProductsCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<ProductsCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productsDestroy = <ThrowOnError extends boolean = false>(options: Options<ProductsDestroyData, ThrowOnError>): RequestResult<ProductsDestroyResponses, unknown, ThrowOnError> => (options.client ?? client).delete<ProductsDestroyResponses, unknown, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/{slug}/',
    ...options
});

export const productsRetrieve = <ThrowOnError extends boolean = false>(options: Options<ProductsRetrieveData, ThrowOnError>): RequestResult<ProductsRetrieveResponses, unknown, ThrowOnError> => (options.client ?? client).get<ProductsRetrieveResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/{slug}/',
    ...options
});

export const productsPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<ProductsPartialUpdateData, ThrowOnError>): RequestResult<ProductsPartialUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).patch<ProductsPartialUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/{slug}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productsUpdate = <ThrowOnError extends boolean = false>(options: Options<ProductsUpdateData, ThrowOnError>): RequestResult<ProductsUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).put<ProductsUpdateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/{slug}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productsDetectAndAssignBrandCreate = <ThrowOnError extends boolean = false>(options: Options<ProductsDetectAndAssignBrandCreateData, ThrowOnError>): RequestResult<ProductsDetectAndAssignBrandCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<ProductsDetectAndAssignBrandCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/{slug}/detect-and-assign-brand/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const productsGenerateSkuCreate = <ThrowOnError extends boolean = false>(options: Options<ProductsGenerateSkuCreateData, ThrowOnError>): RequestResult<ProductsGenerateSkuCreateResponses, unknown, ThrowOnError> => (options.client ?? client).post<ProductsGenerateSkuCreateResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{
            in: 'cookie',
            name: 'sessionid',
            type: 'apiKey'
        }],
    url: '/products/{slug}/generate-sku/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
