// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://schema.yml` | (string & {});
};

export type Brand = {
    readonly id: number;
    slug?: string;
    name: string;
};

export type Category = {
    readonly id: number;
    slug?: string;
    name: string;
    description?: string | null;
};

export type Login = {
    username?: string;
    email?: string;
    password: string;
};

export type PaginatedBrandList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Brand>;
};

export type PaginatedCategoryList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Category>;
};

export type PaginatedProductList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Product>;
};

export type PasswordChange = {
    new_password1: string;
    new_password2: string;
};

/**
 * Serializer for requesting a password reset e-mail.
 */
export type PasswordReset = {
    email: string;
};

/**
 * Serializer for confirming a password reset attempt.
 */
export type PasswordResetConfirm = {
    new_password1: string;
    new_password2: string;
    uid: string;
    token: string;
};

export type PatchedBrand = {
    readonly id?: number;
    slug?: string;
    name?: string;
};

export type PatchedCategory = {
    readonly id?: number;
    slug?: string;
    name?: string;
    description?: string | null;
};

export type PatchedProduct = {
    readonly id?: number;
    brand?: Brand | null;
    brand_id?: number | null;
    category?: Category | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name?: string;
    description?: string | null;
    image?: string | null;
    status?: StatusEnum;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
    readonly created_at?: string;
};

/**
 * User model w/o password
 */
export type PatchedUserDetails = {
    /**
     * ID
     */
    readonly pk?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Email address
     */
    readonly email?: string;
    first_name?: string;
    last_name?: string;
};

export type Product = {
    readonly id: number;
    brand: Brand | null;
    brand_id?: number | null;
    category: Category | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name: string;
    description?: string | null;
    image?: string | null;
    status?: StatusEnum;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
    readonly created_at: string;
};

export type RestAuthDetail = {
    readonly detail: string;
};

/**
 * * `draft` - Draft
 * * `active` - Active
 * * `inactive` - Inactive
 * * `out_of_stock` - Out of stock
 * * `discontinued` - Discontinued
 */
export type StatusEnum = 'draft' | 'active' | 'inactive' | 'out_of_stock' | 'discontinued';

/**
 * Serializer for Token model.
 */
export type Token = {
    key: string;
};

/**
 * User model w/o password
 */
export type UserDetails = {
    /**
     * ID
     */
    readonly pk: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    readonly email: string;
    first_name?: string;
    last_name?: string;
};

export type BrandWritable = {
    slug?: string;
    name: string;
};

export type CategoryWritable = {
    slug?: string;
    name: string;
    description?: string | null;
};

export type PaginatedBrandListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BrandWritable>;
};

export type PaginatedCategoryListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CategoryWritable>;
};

export type PaginatedProductListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ProductWritable>;
};

export type PatchedBrandWritable = {
    slug?: string;
    name?: string;
};

export type PatchedCategoryWritable = {
    slug?: string;
    name?: string;
    description?: string | null;
};

export type PatchedProductWritable = {
    brand_id?: number | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name?: string;
    description?: string | null;
    image?: string | null;
    status?: StatusEnum;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
};

/**
 * User model w/o password
 */
export type PatchedUserDetailsWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    first_name?: string;
    last_name?: string;
};

export type ProductWritable = {
    brand_id?: number | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name: string;
    description?: string | null;
    image?: string | null;
    status?: StatusEnum;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
};

/**
 * User model w/o password
 */
export type UserDetailsWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type AuthLoginCreateData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/auth/login/';
};

export type AuthLoginCreateResponses = {
    200: Token;
};

export type AuthLoginCreateResponse = AuthLoginCreateResponses[keyof AuthLoginCreateResponses];

export type AuthLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout/';
};

export type AuthLogoutCreateResponses = {
    200: RestAuthDetail;
};

export type AuthLogoutCreateResponse = AuthLogoutCreateResponses[keyof AuthLogoutCreateResponses];

export type AuthPasswordChangeCreateData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/auth/password/change/';
};

export type AuthPasswordChangeCreateResponses = {
    200: RestAuthDetail;
};

export type AuthPasswordChangeCreateResponse = AuthPasswordChangeCreateResponses[keyof AuthPasswordChangeCreateResponses];

export type AuthPasswordResetCreateData = {
    body: PasswordReset;
    path?: never;
    query?: never;
    url: '/auth/password/reset/';
};

export type AuthPasswordResetCreateResponses = {
    200: RestAuthDetail;
};

export type AuthPasswordResetCreateResponse = AuthPasswordResetCreateResponses[keyof AuthPasswordResetCreateResponses];

export type AuthPasswordResetConfirmCreateData = {
    body: PasswordResetConfirm;
    path?: never;
    query?: never;
    url: '/auth/password/reset/confirm/';
};

export type AuthPasswordResetConfirmCreateResponses = {
    200: RestAuthDetail;
};

export type AuthPasswordResetConfirmCreateResponse = AuthPasswordResetConfirmCreateResponses[keyof AuthPasswordResetConfirmCreateResponses];

export type AuthUserRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/user/';
};

export type AuthUserRetrieveResponses = {
    200: UserDetails;
};

export type AuthUserRetrieveResponse = AuthUserRetrieveResponses[keyof AuthUserRetrieveResponses];

export type AuthUserPartialUpdateData = {
    body?: PatchedUserDetailsWritable;
    path?: never;
    query?: never;
    url: '/auth/user/';
};

export type AuthUserPartialUpdateResponses = {
    200: UserDetails;
};

export type AuthUserPartialUpdateResponse = AuthUserPartialUpdateResponses[keyof AuthUserPartialUpdateResponses];

export type AuthUserUpdateData = {
    body: UserDetailsWritable;
    path?: never;
    query?: never;
    url: '/auth/user/';
};

export type AuthUserUpdateResponses = {
    200: UserDetails;
};

export type AuthUserUpdateResponse = AuthUserUpdateResponses[keyof AuthUserUpdateResponses];

export type BrandsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/brands/';
};

export type BrandsListResponses = {
    200: PaginatedBrandList;
};

export type BrandsListResponse = BrandsListResponses[keyof BrandsListResponses];

export type BrandsCreateData = {
    body: BrandWritable;
    path?: never;
    query?: never;
    url: '/brands/';
};

export type BrandsCreateResponses = {
    201: Brand;
};

export type BrandsCreateResponse = BrandsCreateResponses[keyof BrandsCreateResponses];

export type BrandsDestroyData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type BrandsDestroyResponse = BrandsDestroyResponses[keyof BrandsDestroyResponses];

export type BrandsRetrieveData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsRetrieveResponses = {
    200: Brand;
};

export type BrandsRetrieveResponse = BrandsRetrieveResponses[keyof BrandsRetrieveResponses];

export type BrandsPartialUpdateData = {
    body?: PatchedBrandWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsPartialUpdateResponses = {
    200: Brand;
};

export type BrandsPartialUpdateResponse = BrandsPartialUpdateResponses[keyof BrandsPartialUpdateResponses];

export type BrandsUpdateData = {
    body: BrandWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsUpdateResponses = {
    200: Brand;
};

export type BrandsUpdateResponse = BrandsUpdateResponses[keyof BrandsUpdateResponses];

export type BrandsListAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/brands/all/';
};

export type BrandsListAllResponses = {
    200: Array<Brand>;
};

export type BrandsListAllResponse = BrandsListAllResponses[keyof BrandsListAllResponses];

export type CategoriesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/categories/';
};

export type CategoriesListResponses = {
    200: PaginatedCategoryList;
};

export type CategoriesListResponse = CategoriesListResponses[keyof CategoriesListResponses];

export type CategoriesCreateData = {
    body: CategoryWritable;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type CategoriesCreateResponses = {
    201: Category;
};

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses];

export type CategoriesDestroyData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CategoriesDestroyResponse = CategoriesDestroyResponses[keyof CategoriesDestroyResponses];

export type CategoriesRetrieveData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesRetrieveResponses = {
    200: Category;
};

export type CategoriesRetrieveResponse = CategoriesRetrieveResponses[keyof CategoriesRetrieveResponses];

export type CategoriesPartialUpdateData = {
    body?: PatchedCategoryWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesPartialUpdateResponses = {
    200: Category;
};

export type CategoriesPartialUpdateResponse = CategoriesPartialUpdateResponses[keyof CategoriesPartialUpdateResponses];

export type CategoriesUpdateData = {
    body: CategoryWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesUpdateResponses = {
    200: Category;
};

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses];

export type CategoriesListAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/categories/all/';
};

export type CategoriesListAllResponses = {
    200: Array<Category>;
};

export type CategoriesListAllResponse = CategoriesListAllResponses[keyof CategoriesListAllResponses];

export type ProductsListData = {
    body?: never;
    path?: never;
    query?: {
        brand?: Array<string>;
        category?: Array<string>;
        created_at_after?: string;
        created_at_before?: string;
        discount_price_max?: number | null;
        discount_price_min?: number | null;
        featured?: boolean;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        price_max?: number | null;
        price_min?: number | null;
        /**
         * A search term.
         */
        search?: string;
        /**
         * * `draft` - Draft
         * * `active` - Active
         * * `inactive` - Inactive
         * * `out_of_stock` - Out of stock
         * * `discontinued` - Discontinued
         */
        status?: Array<'active' | 'discontinued' | 'draft' | 'inactive' | 'out_of_stock'>;
    };
    url: '/products/';
};

export type ProductsListResponses = {
    200: PaginatedProductList;
};

export type ProductsListResponse = ProductsListResponses[keyof ProductsListResponses];

export type ProductsCreateData = {
    body: ProductWritable;
    path?: never;
    query?: never;
    url: '/products/';
};

export type ProductsCreateResponses = {
    201: Product;
};

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses];

export type ProductsDestroyData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProductsDestroyResponse = ProductsDestroyResponses[keyof ProductsDestroyResponses];

export type ProductsRetrieveData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsRetrieveResponses = {
    200: Product;
};

export type ProductsRetrieveResponse = ProductsRetrieveResponses[keyof ProductsRetrieveResponses];

export type ProductsPartialUpdateData = {
    body?: PatchedProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsPartialUpdateResponses = {
    200: Product;
};

export type ProductsPartialUpdateResponse = ProductsPartialUpdateResponses[keyof ProductsPartialUpdateResponses];

export type ProductsUpdateData = {
    body: ProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsUpdateResponses = {
    200: Product;
};

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses];

export type ProductsDetectAndAssignBrandCreateData = {
    body: ProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/detect-and-assign-brand/';
};

export type ProductsDetectAndAssignBrandCreateResponses = {
    200: Product;
};

export type ProductsDetectAndAssignBrandCreateResponse = ProductsDetectAndAssignBrandCreateResponses[keyof ProductsDetectAndAssignBrandCreateResponses];

export type ProductsGenerateSkuCreateData = {
    body: ProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/generate-sku/';
};

export type ProductsGenerateSkuCreateResponses = {
    200: Product;
};

export type ProductsGenerateSkuCreateResponse = ProductsGenerateSkuCreateResponses[keyof ProductsGenerateSkuCreateResponses];
