// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://schema.yml` | (string & {});
};

export type BlankEnum = '';

export type Brand = {
    readonly id: number;
    slug?: string;
    name: string;
};

export type Category = {
    readonly id: number;
    slug?: string;
    name: string;
    description?: string | null;
};

export type Customer = {
    readonly id: number;
    name: string;
    email?: string;
    phone?: string;
};

export type Login = {
    username?: string;
    email?: string;
    password: string;
};

export type Order = {
    readonly id: number;
    readonly items: Array<OrderItem>;
    readonly total: number;
    customer_detail: Customer;
    status?: OrderStatus | BlankEnum;
    readonly created_at: string;
    readonly updated_at: string;
    customer: number;
};

export type OrderCreate = {
    readonly id: number;
    items: Array<OrderItem>;
    readonly total: number;
    customer_detail: Customer;
    status?: OrderStatus | BlankEnum;
    readonly created_at: string;
    readonly updated_at: string;
    customer: number;
};

export type OrderItem = {
    readonly id: number;
    readonly subtotal: number;
    product_detail: ProductSummary;
    product: number;
    quantity?: number;
    readonly unit_price: number;
};

/**
 * * `pending` - Pending
 * * `paid` - Paid
 * * `shipped` - Shipped
 * * `delivered` - Delivered
 * * `cancelled` - Cancelled
 */
export type OrderStatus = 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled';

export type PaginatedBrandList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Brand>;
};

export type PaginatedCategoryList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Category>;
};

export type PaginatedCustomerList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Customer>;
};

export type PaginatedOrderList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Order>;
};

export type PaginatedProductList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Product>;
};

export type PasswordChange = {
    new_password1: string;
    new_password2: string;
};

/**
 * Serializer for requesting a password reset e-mail.
 */
export type PasswordReset = {
    email: string;
};

/**
 * Serializer for confirming a password reset attempt.
 */
export type PasswordResetConfirm = {
    new_password1: string;
    new_password2: string;
    uid: string;
    token: string;
};

export type PatchedBrand = {
    readonly id?: number;
    slug?: string;
    name?: string;
};

export type PatchedCategory = {
    readonly id?: number;
    slug?: string;
    name?: string;
    description?: string | null;
};

export type PatchedCustomer = {
    readonly id?: number;
    name?: string;
    email?: string;
    phone?: string;
};

export type PatchedOrder = {
    readonly id?: number;
    readonly items?: Array<OrderItem>;
    readonly total?: number;
    customer_detail?: Customer;
    status?: OrderStatus | BlankEnum;
    readonly created_at?: string;
    readonly updated_at?: string;
    customer?: number;
};

export type PatchedProduct = {
    readonly id?: number;
    brand?: Brand | null;
    brand_id?: number | null;
    category?: Category | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name?: string;
    description?: string | null;
    image?: string | null;
    status?: ProductStatus;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
    readonly created_at?: string;
};

/**
 * User model w/o password
 */
export type PatchedUserDetails = {
    /**
     * ID
     */
    readonly pk?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Email address
     */
    readonly email?: string;
    first_name?: string;
    last_name?: string;
};

export type Product = {
    readonly id: number;
    brand: Brand | null;
    brand_id?: number | null;
    category: Category | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name: string;
    description?: string | null;
    image?: string | null;
    status?: ProductStatus;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
    readonly created_at: string;
};

/**
 * * `draft` - Draft
 * * `active` - Active
 * * `inactive` - Inactive
 * * `out_of_stock` - Out of stock
 * * `discontinued` - Discontinued
 */
export type ProductStatus = 'draft' | 'active' | 'inactive' | 'out_of_stock' | 'discontinued';

export type ProductSummary = {
    readonly id: number;
    readonly slug: string;
    readonly name: string;
};

export type RestAuthDetail = {
    readonly detail: string;
};

/**
 * Serializer for Token model.
 */
export type Token = {
    key: string;
};

/**
 * User model w/o password
 */
export type UserDetails = {
    /**
     * ID
     */
    readonly pk: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    readonly email: string;
    first_name?: string;
    last_name?: string;
};

export type BrandWritable = {
    slug?: string;
    name: string;
};

export type CategoryWritable = {
    slug?: string;
    name: string;
    description?: string | null;
};

export type CustomerWritable = {
    name: string;
    email?: string;
    phone?: string;
};

export type OrderWritable = {
    status?: OrderStatus | BlankEnum;
    customer: number;
};

export type OrderCreateWritable = {
    items: Array<OrderItemWritable>;
    status?: OrderStatus | BlankEnum;
    customer: number;
};

export type OrderItemWritable = {
    product: number;
    quantity?: number;
};

export type PaginatedBrandListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<BrandWritable>;
};

export type PaginatedCategoryListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CategoryWritable>;
};

export type PaginatedCustomerListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<CustomerWritable>;
};

export type PaginatedOrderListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<OrderWritable>;
};

export type PaginatedProductListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<ProductWritable>;
};

export type PatchedBrandWritable = {
    slug?: string;
    name?: string;
};

export type PatchedCategoryWritable = {
    slug?: string;
    name?: string;
    description?: string | null;
};

export type PatchedCustomerWritable = {
    name?: string;
    email?: string;
    phone?: string;
};

export type PatchedOrderWritable = {
    status?: OrderStatus | BlankEnum;
    customer?: number;
};

export type PatchedProductWritable = {
    brand_id?: number | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name?: string;
    description?: string | null;
    image?: string | null;
    status?: ProductStatus;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
};

/**
 * User model w/o password
 */
export type PatchedUserDetailsWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    first_name?: string;
    last_name?: string;
};

export type ProductWritable = {
    brand_id?: number | null;
    category_id?: number | null;
    slug?: string;
    sku?: string | null;
    name: string;
    description?: string | null;
    image?: string | null;
    status?: ProductStatus;
    featured?: boolean;
    price?: number | null;
    discount_price?: number | null;
};

/**
 * User model w/o password
 */
export type UserDetailsWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type AuthLoginCreateData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/auth/login/';
};

export type AuthLoginCreateResponses = {
    200: Token;
};

export type AuthLoginCreateResponse = AuthLoginCreateResponses[keyof AuthLoginCreateResponses];

export type AuthLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout/';
};

export type AuthLogoutCreateResponses = {
    200: RestAuthDetail;
};

export type AuthLogoutCreateResponse = AuthLogoutCreateResponses[keyof AuthLogoutCreateResponses];

export type AuthPasswordChangeCreateData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/auth/password/change/';
};

export type AuthPasswordChangeCreateResponses = {
    200: RestAuthDetail;
};

export type AuthPasswordChangeCreateResponse = AuthPasswordChangeCreateResponses[keyof AuthPasswordChangeCreateResponses];

export type AuthPasswordResetCreateData = {
    body: PasswordReset;
    path?: never;
    query?: never;
    url: '/auth/password/reset/';
};

export type AuthPasswordResetCreateResponses = {
    200: RestAuthDetail;
};

export type AuthPasswordResetCreateResponse = AuthPasswordResetCreateResponses[keyof AuthPasswordResetCreateResponses];

export type AuthPasswordResetConfirmCreateData = {
    body: PasswordResetConfirm;
    path?: never;
    query?: never;
    url: '/auth/password/reset/confirm/';
};

export type AuthPasswordResetConfirmCreateResponses = {
    200: RestAuthDetail;
};

export type AuthPasswordResetConfirmCreateResponse = AuthPasswordResetConfirmCreateResponses[keyof AuthPasswordResetConfirmCreateResponses];

export type AuthUserRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/user/';
};

export type AuthUserRetrieveResponses = {
    200: UserDetails;
};

export type AuthUserRetrieveResponse = AuthUserRetrieveResponses[keyof AuthUserRetrieveResponses];

export type AuthUserPartialUpdateData = {
    body?: PatchedUserDetailsWritable;
    path?: never;
    query?: never;
    url: '/auth/user/';
};

export type AuthUserPartialUpdateResponses = {
    200: UserDetails;
};

export type AuthUserPartialUpdateResponse = AuthUserPartialUpdateResponses[keyof AuthUserPartialUpdateResponses];

export type AuthUserUpdateData = {
    body: UserDetailsWritable;
    path?: never;
    query?: never;
    url: '/auth/user/';
};

export type AuthUserUpdateResponses = {
    200: UserDetails;
};

export type AuthUserUpdateResponse = AuthUserUpdateResponses[keyof AuthUserUpdateResponses];

export type BrandsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/brands/';
};

export type BrandsListResponses = {
    200: PaginatedBrandList;
};

export type BrandsListResponse = BrandsListResponses[keyof BrandsListResponses];

export type BrandsCreateData = {
    body: BrandWritable;
    path?: never;
    query?: never;
    url: '/brands/';
};

export type BrandsCreateResponses = {
    201: Brand;
};

export type BrandsCreateResponse = BrandsCreateResponses[keyof BrandsCreateResponses];

export type BrandsDestroyData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type BrandsDestroyResponse = BrandsDestroyResponses[keyof BrandsDestroyResponses];

export type BrandsRetrieveData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsRetrieveResponses = {
    200: Brand;
};

export type BrandsRetrieveResponse = BrandsRetrieveResponses[keyof BrandsRetrieveResponses];

export type BrandsPartialUpdateData = {
    body?: PatchedBrandWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsPartialUpdateResponses = {
    200: Brand;
};

export type BrandsPartialUpdateResponse = BrandsPartialUpdateResponses[keyof BrandsPartialUpdateResponses];

export type BrandsUpdateData = {
    body: BrandWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/brands/{slug}/';
};

export type BrandsUpdateResponses = {
    200: Brand;
};

export type BrandsUpdateResponse = BrandsUpdateResponses[keyof BrandsUpdateResponses];

export type BrandsListAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/brands/all/';
};

export type BrandsListAllResponses = {
    200: Array<Brand>;
};

export type BrandsListAllResponse = BrandsListAllResponses[keyof BrandsListAllResponses];

export type CategoriesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/categories/';
};

export type CategoriesListResponses = {
    200: PaginatedCategoryList;
};

export type CategoriesListResponse = CategoriesListResponses[keyof CategoriesListResponses];

export type CategoriesCreateData = {
    body: CategoryWritable;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type CategoriesCreateResponses = {
    201: Category;
};

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses];

export type CategoriesDestroyData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CategoriesDestroyResponse = CategoriesDestroyResponses[keyof CategoriesDestroyResponses];

export type CategoriesRetrieveData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesRetrieveResponses = {
    200: Category;
};

export type CategoriesRetrieveResponse = CategoriesRetrieveResponses[keyof CategoriesRetrieveResponses];

export type CategoriesPartialUpdateData = {
    body?: PatchedCategoryWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesPartialUpdateResponses = {
    200: Category;
};

export type CategoriesPartialUpdateResponse = CategoriesPartialUpdateResponses[keyof CategoriesPartialUpdateResponses];

export type CategoriesUpdateData = {
    body: CategoryWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/categories/{slug}/';
};

export type CategoriesUpdateResponses = {
    200: Category;
};

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses];

export type CategoriesListAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/categories/all/';
};

export type CategoriesListAllResponses = {
    200: Array<Category>;
};

export type CategoriesListAllResponse = CategoriesListAllResponses[keyof CategoriesListAllResponses];

export type CustomersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/customers/';
};

export type CustomersListResponses = {
    200: PaginatedCustomerList;
};

export type CustomersListResponse = CustomersListResponses[keyof CustomersListResponses];

export type CustomersCreateData = {
    body: CustomerWritable;
    path?: never;
    query?: never;
    url: '/customers/';
};

export type CustomersCreateResponses = {
    201: Customer;
};

export type CustomersCreateResponse = CustomersCreateResponses[keyof CustomersCreateResponses];

export type CustomersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this customer.
         */
        id: number;
    };
    query?: never;
    url: '/customers/{id}/';
};

export type CustomersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type CustomersDestroyResponse = CustomersDestroyResponses[keyof CustomersDestroyResponses];

export type CustomersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this customer.
         */
        id: number;
    };
    query?: never;
    url: '/customers/{id}/';
};

export type CustomersRetrieveResponses = {
    200: Customer;
};

export type CustomersRetrieveResponse = CustomersRetrieveResponses[keyof CustomersRetrieveResponses];

export type CustomersPartialUpdateData = {
    body?: PatchedCustomerWritable;
    path: {
        /**
         * A unique integer value identifying this customer.
         */
        id: number;
    };
    query?: never;
    url: '/customers/{id}/';
};

export type CustomersPartialUpdateResponses = {
    200: Customer;
};

export type CustomersPartialUpdateResponse = CustomersPartialUpdateResponses[keyof CustomersPartialUpdateResponses];

export type CustomersUpdateData = {
    body: CustomerWritable;
    path: {
        /**
         * A unique integer value identifying this customer.
         */
        id: number;
    };
    query?: never;
    url: '/customers/{id}/';
};

export type CustomersUpdateResponses = {
    200: Customer;
};

export type CustomersUpdateResponse = CustomersUpdateResponses[keyof CustomersUpdateResponses];

export type CustomersListAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/customers/all/';
};

export type CustomersListAllResponses = {
    200: Array<Customer>;
};

export type CustomersListAllResponse = CustomersListAllResponses[keyof CustomersListAllResponses];

export type OrdersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/orders/';
};

export type OrdersListResponses = {
    200: PaginatedOrderList;
};

export type OrdersListResponse = OrdersListResponses[keyof OrdersListResponses];

export type OrdersCreateData = {
    body: OrderCreateWritable;
    path?: never;
    query?: never;
    url: '/orders/';
};

export type OrdersCreateResponses = {
    201: OrderCreate;
};

export type OrdersCreateResponse = OrdersCreateResponses[keyof OrdersCreateResponses];

export type OrdersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/orders/{id}/';
};

export type OrdersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type OrdersDestroyResponse = OrdersDestroyResponses[keyof OrdersDestroyResponses];

export type OrdersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/orders/{id}/';
};

export type OrdersRetrieveResponses = {
    200: Order;
};

export type OrdersRetrieveResponse = OrdersRetrieveResponses[keyof OrdersRetrieveResponses];

export type OrdersPartialUpdateData = {
    body?: PatchedOrderWritable;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/orders/{id}/';
};

export type OrdersPartialUpdateResponses = {
    200: Order;
};

export type OrdersPartialUpdateResponse = OrdersPartialUpdateResponses[keyof OrdersPartialUpdateResponses];

export type OrdersUpdateData = {
    body: OrderWritable;
    path: {
        /**
         * A unique integer value identifying this order.
         */
        id: number;
    };
    query?: never;
    url: '/orders/{id}/';
};

export type OrdersUpdateResponses = {
    200: Order;
};

export type OrdersUpdateResponse = OrdersUpdateResponses[keyof OrdersUpdateResponses];

export type ProductsListData = {
    body?: never;
    path?: never;
    query?: {
        brand?: Array<string>;
        category?: Array<string>;
        created_at_after?: string;
        created_at_before?: string;
        discount_price_max?: number | null;
        discount_price_min?: number | null;
        featured?: boolean;
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        price_max?: number | null;
        price_min?: number | null;
        /**
         * A search term.
         */
        search?: string;
        /**
         * * `draft` - Draft
         * * `active` - Active
         * * `inactive` - Inactive
         * * `out_of_stock` - Out of stock
         * * `discontinued` - Discontinued
         */
        status?: Array<'active' | 'discontinued' | 'draft' | 'inactive' | 'out_of_stock'>;
    };
    url: '/products/';
};

export type ProductsListResponses = {
    200: PaginatedProductList;
};

export type ProductsListResponse = ProductsListResponses[keyof ProductsListResponses];

export type ProductsCreateData = {
    body: ProductWritable;
    path?: never;
    query?: never;
    url: '/products/';
};

export type ProductsCreateResponses = {
    201: Product;
};

export type ProductsCreateResponse = ProductsCreateResponses[keyof ProductsCreateResponses];

export type ProductsDestroyData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type ProductsDestroyResponse = ProductsDestroyResponses[keyof ProductsDestroyResponses];

export type ProductsRetrieveData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsRetrieveResponses = {
    200: Product;
};

export type ProductsRetrieveResponse = ProductsRetrieveResponses[keyof ProductsRetrieveResponses];

export type ProductsPartialUpdateData = {
    body?: PatchedProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsPartialUpdateResponses = {
    200: Product;
};

export type ProductsPartialUpdateResponse = ProductsPartialUpdateResponses[keyof ProductsPartialUpdateResponses];

export type ProductsUpdateData = {
    body: ProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/';
};

export type ProductsUpdateResponses = {
    200: Product;
};

export type ProductsUpdateResponse = ProductsUpdateResponses[keyof ProductsUpdateResponses];

export type ProductsDetectAndAssignBrandCreateData = {
    body: ProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/detect-and-assign-brand/';
};

export type ProductsDetectAndAssignBrandCreateResponses = {
    200: Product;
};

export type ProductsDetectAndAssignBrandCreateResponse = ProductsDetectAndAssignBrandCreateResponses[keyof ProductsDetectAndAssignBrandCreateResponses];

export type ProductsGenerateSkuCreateData = {
    body: ProductWritable;
    path: {
        slug: string;
    };
    query?: never;
    url: '/products/{slug}/generate-sku/';
};

export type ProductsGenerateSkuCreateResponses = {
    200: Product;
};

export type ProductsGenerateSkuCreateResponse = ProductsGenerateSkuCreateResponses[keyof ProductsGenerateSkuCreateResponses];

export type ProductsListAllData = {
    body?: never;
    path?: never;
    query?: {
        brand?: Array<string>;
        category?: Array<string>;
        created_at_after?: string;
        created_at_before?: string;
        discount_price_max?: number | null;
        discount_price_min?: number | null;
        featured?: boolean;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        price_max?: number | null;
        price_min?: number | null;
        /**
         * A search term.
         */
        search?: string;
        /**
         * * `draft` - Draft
         * * `active` - Active
         * * `inactive` - Inactive
         * * `out_of_stock` - Out of stock
         * * `discontinued` - Discontinued
         */
        status?: Array<'active' | 'discontinued' | 'draft' | 'inactive' | 'out_of_stock'>;
    };
    url: '/products/all/';
};

export type ProductsListAllResponses = {
    200: Array<Product>;
};

export type ProductsListAllResponse = ProductsListAllResponses[keyof ProductsListAllResponses];
