// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBlankEnum = z.enum(['']);

export const zBrand = z.object({
    id: z.int().readonly(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255)
});

export const zCategory = z.object({
    id: z.int().readonly(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255),
    description: z.string().nullish()
});

export const zLogin = z.object({
    username: z.string().optional(),
    email: z.email().optional(),
    password: z.string()
});

/**
 * * `pending` - Pending
 * * `paid` - Paid
 * * `shipped` - Shipped
 * * `delivered` - Delivered
 * * `cancelled` - Cancelled
 */
export const zOrderStatus = z.enum([
    'pending',
    'paid',
    'shipped',
    'delivered',
    'cancelled'
]);

export const zPaginatedBrandList = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zBrand)
});

export const zPaginatedCategoryList = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zCategory)
});

export const zPasswordChange = z.object({
    new_password1: z.string().max(128),
    new_password2: z.string().max(128)
});

/**
 * Serializer for requesting a password reset e-mail.
 */
export const zPasswordReset = z.object({
    email: z.email()
});

/**
 * Serializer for confirming a password reset attempt.
 */
export const zPasswordResetConfirm = z.object({
    new_password1: z.string().max(128),
    new_password2: z.string().max(128),
    uid: z.string(),
    token: z.string()
});

export const zPatchedBrand = z.object({
    id: z.int().readonly().optional(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255).optional()
});

export const zPatchedCategory = z.object({
    id: z.int().readonly().optional(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255).optional(),
    description: z.string().nullish()
});

/**
 * User model w/o password
 */
export const zPatchedUserDetails = z.object({
    pk: z.int().readonly().optional(),
    username: z.string().max(150).regex(/^[\w.@+-]+$/).optional(),
    email: z.email().readonly().optional(),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional()
});

/**
 * * `draft` - Draft
 * * `active` - Active
 * * `inactive` - Inactive
 * * `out_of_stock` - Out of stock
 * * `discontinued` - Discontinued
 */
export const zProductStatus = z.enum([
    'draft',
    'active',
    'inactive',
    'out_of_stock',
    'discontinued'
]);

export const zPatchedProduct = z.object({
    id: z.int().readonly().optional(),
    brand: zBrand.nullish(),
    brand_id: z.int().nullish(),
    category: zCategory.nullish(),
    category_id: z.int().nullish(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    sku: z.string().max(255).nullish(),
    name: z.string().max(255).optional(),
    description: z.string().nullish(),
    image: z.url().nullish(),
    status: zProductStatus.optional(),
    featured: z.boolean().optional(),
    price: z.int().gte(0).lte(2147483647).nullish(),
    discount_price: z.int().gte(0).lte(2147483647).nullish(),
    created_at: z.iso.datetime().readonly().optional()
});

export const zProduct = z.object({
    id: z.int().readonly(),
    brand: zBrand.nullable(),
    brand_id: z.int().nullish(),
    category: zCategory.nullable(),
    category_id: z.int().nullish(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    sku: z.string().max(255).nullish(),
    name: z.string().max(255),
    description: z.string().nullish(),
    image: z.url().nullish(),
    status: zProductStatus.optional(),
    featured: z.boolean().optional(),
    price: z.int().gte(0).lte(2147483647).nullish(),
    discount_price: z.int().gte(0).lte(2147483647).nullish(),
    created_at: z.iso.datetime().readonly()
});

export const zPaginatedProductList = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zProduct)
});

export const zProductSummary = z.object({
    id: z.int().readonly(),
    slug: z.string().readonly(),
    name: z.string().readonly()
});

export const zOrderItem = z.object({
    id: z.int().readonly(),
    subtotal: z.int(),
    product_detail: zProductSummary,
    product: z.int(),
    quantity: z.int().gte(0).lte(2147483647).optional(),
    unit_price: z.int().readonly()
});

export const zOrder = z.object({
    id: z.int().readonly(),
    items: z.array(zOrderItem).readonly(),
    total: z.int().readonly(),
    customer_detail: z.string().readonly(),
    status: z.union([
        zOrderStatus,
        zBlankEnum
    ]).optional(),
    created_at: z.iso.datetime().readonly(),
    updated_at: z.iso.datetime().readonly(),
    customer: z.int()
});

export const zOrderCreate = z.object({
    id: z.int().readonly(),
    items: z.array(zOrderItem),
    total: z.int().readonly(),
    customer_detail: z.string().readonly(),
    status: z.union([
        zOrderStatus,
        zBlankEnum
    ]).optional(),
    created_at: z.iso.datetime().readonly(),
    updated_at: z.iso.datetime().readonly(),
    customer: z.int()
});

export const zPaginatedOrderList = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zOrder)
});

export const zPatchedOrder = z.object({
    id: z.int().readonly().optional(),
    items: z.array(zOrderItem).readonly().optional(),
    total: z.int().readonly().optional(),
    customer_detail: z.string().readonly().optional(),
    status: z.union([
        zOrderStatus,
        zBlankEnum
    ]).optional(),
    created_at: z.iso.datetime().readonly().optional(),
    updated_at: z.iso.datetime().readonly().optional(),
    customer: z.int().optional()
});

export const zRestAuthDetail = z.object({
    detail: z.string().readonly()
});

/**
 * Serializer for Token model.
 */
export const zToken = z.object({
    key: z.string().max(40)
});

/**
 * User model w/o password
 */
export const zUserDetails = z.object({
    pk: z.int().readonly(),
    username: z.string().max(150).regex(/^[\w.@+-]+$/),
    email: z.email().readonly(),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional()
});

export const zBrandWritable = z.object({
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255)
});

export const zCategoryWritable = z.object({
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255),
    description: z.string().nullish()
});

export const zOrderWritable = z.object({
    status: z.union([
        zOrderStatus,
        zBlankEnum
    ]).optional(),
    customer: z.int()
});

export const zOrderItemWritable = z.object({
    subtotal: z.int(),
    product: z.int(),
    quantity: z.int().gte(0).lte(2147483647).optional()
});

export const zOrderCreateWritable = z.object({
    items: z.array(zOrderItemWritable),
    status: z.union([
        zOrderStatus,
        zBlankEnum
    ]).optional(),
    customer: z.int()
});

export const zPaginatedBrandListWritable = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zBrandWritable)
});

export const zPaginatedCategoryListWritable = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zCategoryWritable)
});

export const zPaginatedOrderListWritable = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zOrderWritable)
});

export const zPatchedBrandWritable = z.object({
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255).optional()
});

export const zPatchedCategoryWritable = z.object({
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    name: z.string().max(255).optional(),
    description: z.string().nullish()
});

export const zPatchedOrderWritable = z.object({
    status: z.union([
        zOrderStatus,
        zBlankEnum
    ]).optional(),
    customer: z.int().optional()
});

export const zPatchedProductWritable = z.object({
    brand_id: z.int().nullish(),
    category_id: z.int().nullish(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    sku: z.string().max(255).nullish(),
    name: z.string().max(255).optional(),
    description: z.string().nullish(),
    image: z.url().nullish(),
    status: zProductStatus.optional(),
    featured: z.boolean().optional(),
    price: z.int().gte(0).lte(2147483647).nullish(),
    discount_price: z.int().gte(0).lte(2147483647).nullish()
});

/**
 * User model w/o password
 */
export const zPatchedUserDetailsWritable = z.object({
    username: z.string().max(150).regex(/^[\w.@+-]+$/).optional(),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional()
});

export const zProductWritable = z.object({
    brand_id: z.int().nullish(),
    category_id: z.int().nullish(),
    slug: z.string().max(255).regex(/^[-a-zA-Z0-9_]+$/).optional(),
    sku: z.string().max(255).nullish(),
    name: z.string().max(255),
    description: z.string().nullish(),
    image: z.url().nullish(),
    status: zProductStatus.optional(),
    featured: z.boolean().optional(),
    price: z.int().gte(0).lte(2147483647).nullish(),
    discount_price: z.int().gte(0).lte(2147483647).nullish()
});

export const zPaginatedProductListWritable = z.object({
    count: z.int(),
    next: z.url().nullish(),
    previous: z.url().nullish(),
    results: z.array(zProductWritable)
});

/**
 * User model w/o password
 */
export const zUserDetailsWritable = z.object({
    username: z.string().max(150).regex(/^[\w.@+-]+$/),
    first_name: z.string().max(150).optional(),
    last_name: z.string().max(150).optional()
});

export const zAuthLoginCreateBody = zLogin;

export const zAuthLoginCreateResponse = zToken;

export const zAuthLogoutCreateResponse = zRestAuthDetail;

export const zAuthPasswordChangeCreateBody = zPasswordChange;

export const zAuthPasswordChangeCreateResponse = zRestAuthDetail;

export const zAuthPasswordResetCreateBody = zPasswordReset;

export const zAuthPasswordResetCreateResponse = zRestAuthDetail;

export const zAuthPasswordResetConfirmCreateBody = zPasswordResetConfirm;

export const zAuthPasswordResetConfirmCreateResponse = zRestAuthDetail;

export const zAuthUserRetrieveResponse = zUserDetails;

export const zAuthUserPartialUpdateBody = zPatchedUserDetailsWritable;

export const zAuthUserPartialUpdateResponse = zUserDetails;

export const zAuthUserUpdateBody = zUserDetailsWritable;

export const zAuthUserUpdateResponse = zUserDetails;

export const zBrandsListQuery = z.object({
    limit: z.int().optional(),
    offset: z.int().optional()
});

export const zBrandsListResponse = zPaginatedBrandList;

export const zBrandsCreateBody = zBrandWritable;

export const zBrandsCreateResponse = zBrand;

export const zBrandsDestroyPath = z.object({
    slug: z.string()
});

/**
 * No response body
 */
export const zBrandsDestroyResponse = z.void();

export const zBrandsRetrievePath = z.object({
    slug: z.string()
});

export const zBrandsRetrieveResponse = zBrand;

export const zBrandsPartialUpdateBody = zPatchedBrandWritable;

export const zBrandsPartialUpdatePath = z.object({
    slug: z.string()
});

export const zBrandsPartialUpdateResponse = zBrand;

export const zBrandsUpdateBody = zBrandWritable;

export const zBrandsUpdatePath = z.object({
    slug: z.string()
});

export const zBrandsUpdateResponse = zBrand;

export const zBrandsListAllResponse = z.array(zBrand);

export const zCategoriesListQuery = z.object({
    limit: z.int().optional(),
    offset: z.int().optional(),
    search: z.string().optional()
});

export const zCategoriesListResponse = zPaginatedCategoryList;

export const zCategoriesCreateBody = zCategoryWritable;

export const zCategoriesCreateResponse = zCategory;

export const zCategoriesDestroyPath = z.object({
    slug: z.string()
});

/**
 * No response body
 */
export const zCategoriesDestroyResponse = z.void();

export const zCategoriesRetrievePath = z.object({
    slug: z.string()
});

export const zCategoriesRetrieveResponse = zCategory;

export const zCategoriesPartialUpdateBody = zPatchedCategoryWritable;

export const zCategoriesPartialUpdatePath = z.object({
    slug: z.string()
});

export const zCategoriesPartialUpdateResponse = zCategory;

export const zCategoriesUpdateBody = zCategoryWritable;

export const zCategoriesUpdatePath = z.object({
    slug: z.string()
});

export const zCategoriesUpdateResponse = zCategory;

export const zCategoriesListAllQuery = z.object({
    search: z.string().optional()
});

export const zCategoriesListAllResponse = z.array(zCategory);

export const zOrdersListQuery = z.object({
    limit: z.int().optional(),
    offset: z.int().optional()
});

export const zOrdersListResponse = zPaginatedOrderList;

export const zOrdersCreateBody = zOrderCreateWritable;

export const zOrdersCreateResponse = zOrderCreate;

export const zOrdersDestroyPath = z.object({
    id: z.int()
});

/**
 * No response body
 */
export const zOrdersDestroyResponse = z.void();

export const zOrdersRetrievePath = z.object({
    id: z.int()
});

export const zOrdersRetrieveResponse = zOrder;

export const zOrdersPartialUpdateBody = zPatchedOrderWritable;

export const zOrdersPartialUpdatePath = z.object({
    id: z.int()
});

export const zOrdersPartialUpdateResponse = zOrder;

export const zOrdersUpdateBody = zOrderWritable;

export const zOrdersUpdatePath = z.object({
    id: z.int()
});

export const zOrdersUpdateResponse = zOrder;

export const zProductsListQuery = z.object({
    brand: z.array(z.string()).optional(),
    category: z.array(z.string()).optional(),
    created_at_after: z.iso.date().optional(),
    created_at_before: z.iso.date().optional(),
    discount_price_max: z.int().gte(0).lte(2147483647).nullish(),
    discount_price_min: z.int().gte(0).lte(2147483647).nullish(),
    featured: z.boolean().optional(),
    limit: z.int().optional(),
    offset: z.int().optional(),
    ordering: z.string().optional(),
    price_max: z.int().gte(0).lte(2147483647).nullish(),
    price_min: z.int().gte(0).lte(2147483647).nullish(),
    search: z.string().optional(),
    status: z.array(z.enum([
        'active',
        'discontinued',
        'draft',
        'inactive',
        'out_of_stock'
    ])).optional()
});

export const zProductsListResponse = zPaginatedProductList;

export const zProductsCreateBody = zProductWritable;

export const zProductsCreateResponse = zProduct;

export const zProductsDestroyPath = z.object({
    slug: z.string()
});

/**
 * No response body
 */
export const zProductsDestroyResponse = z.void();

export const zProductsRetrievePath = z.object({
    slug: z.string()
});

export const zProductsRetrieveResponse = zProduct;

export const zProductsPartialUpdateBody = zPatchedProductWritable;

export const zProductsPartialUpdatePath = z.object({
    slug: z.string()
});

export const zProductsPartialUpdateResponse = zProduct;

export const zProductsUpdateBody = zProductWritable;

export const zProductsUpdatePath = z.object({
    slug: z.string()
});

export const zProductsUpdateResponse = zProduct;

export const zProductsDetectAndAssignBrandCreateBody = zProductWritable;

export const zProductsDetectAndAssignBrandCreatePath = z.object({
    slug: z.string()
});

export const zProductsDetectAndAssignBrandCreateResponse = zProduct;

export const zProductsGenerateSkuCreateBody = zProductWritable;

export const zProductsGenerateSkuCreatePath = z.object({
    slug: z.string()
});

export const zProductsGenerateSkuCreateResponse = zProduct;
