// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { authLoginCreate, authLogoutCreate, authPasswordChangeCreate, authPasswordResetConfirmCreate, authPasswordResetCreate, authUserPartialUpdate, authUserRetrieve, authUserUpdate, brandsCreate, brandsDestroy, brandsList, brandsListAll, brandsPartialUpdate, brandsRetrieve, brandsUpdate, categoriesCreate, categoriesDestroy, categoriesList, categoriesListAll, categoriesPartialUpdate, categoriesRetrieve, categoriesUpdate, type Options, ordersCreate, ordersDestroy, ordersList, ordersPartialUpdate, ordersRetrieve, ordersUpdate, productsCreate, productsDestroy, productsDetectAndAssignBrandCreate, productsGenerateSkuCreate, productsList, productsPartialUpdate, productsRetrieve, productsUpdate } from '../sdk.gen';
import type { AuthLoginCreateData, AuthLoginCreateResponse, AuthLogoutCreateData, AuthLogoutCreateResponse, AuthPasswordChangeCreateData, AuthPasswordChangeCreateResponse, AuthPasswordResetConfirmCreateData, AuthPasswordResetConfirmCreateResponse, AuthPasswordResetCreateData, AuthPasswordResetCreateResponse, AuthUserPartialUpdateData, AuthUserPartialUpdateResponse, AuthUserRetrieveData, AuthUserRetrieveResponse, AuthUserUpdateData, AuthUserUpdateResponse, BrandsCreateData, BrandsCreateResponse, BrandsDestroyData, BrandsDestroyResponse, BrandsListAllData, BrandsListAllResponse, BrandsListData, BrandsListResponse, BrandsPartialUpdateData, BrandsPartialUpdateResponse, BrandsRetrieveData, BrandsRetrieveResponse, BrandsUpdateData, BrandsUpdateResponse, CategoriesCreateData, CategoriesCreateResponse, CategoriesDestroyData, CategoriesDestroyResponse, CategoriesListAllData, CategoriesListAllResponse, CategoriesListData, CategoriesListResponse, CategoriesPartialUpdateData, CategoriesPartialUpdateResponse, CategoriesRetrieveData, CategoriesRetrieveResponse, CategoriesUpdateData, CategoriesUpdateResponse, OrdersCreateData, OrdersCreateResponse, OrdersDestroyData, OrdersDestroyResponse, OrdersListData, OrdersListResponse, OrdersPartialUpdateData, OrdersPartialUpdateResponse, OrdersRetrieveData, OrdersRetrieveResponse, OrdersUpdateData, OrdersUpdateResponse, ProductsCreateData, ProductsCreateResponse, ProductsDestroyData, ProductsDestroyResponse, ProductsDetectAndAssignBrandCreateData, ProductsDetectAndAssignBrandCreateResponse, ProductsGenerateSkuCreateData, ProductsGenerateSkuCreateResponse, ProductsListData, ProductsListResponse, ProductsPartialUpdateData, ProductsPartialUpdateResponse, ProductsRetrieveData, ProductsRetrieveResponse, ProductsUpdateData, ProductsUpdateResponse } from '../types.gen';

/**
 * Check the credentials and return the REST Token
 * if the credentials are valid and authenticated.
 * Calls Django Auth login method to register User ID
 * in Django session framework
 *
 * Accept the following POST parameters: username, password
 * Return the REST Framework Token Object's key.
 */
export const authLoginCreateMutation = (options?: Partial<Options<AuthLoginCreateData>>): UseMutationOptions<AuthLoginCreateResponse, AxiosError<DefaultError>, Options<AuthLoginCreateData>> => {
    const mutationOptions: UseMutationOptions<AuthLoginCreateResponse, AxiosError<DefaultError>, Options<AuthLoginCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLoginCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Calls Django logout method and delete the Token object
 * assigned to the current User object.
 *
 * Accepts/Returns nothing.
 */
export const authLogoutCreateMutation = (options?: Partial<Options<AuthLogoutCreateData>>): UseMutationOptions<AuthLogoutCreateResponse, AxiosError<DefaultError>, Options<AuthLogoutCreateData>> => {
    const mutationOptions: UseMutationOptions<AuthLogoutCreateResponse, AxiosError<DefaultError>, Options<AuthLogoutCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authLogoutCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Calls Django Auth SetPasswordForm save method.
 *
 * Accepts the following POST parameters: new_password1, new_password2
 * Returns the success/fail message.
 */
export const authPasswordChangeCreateMutation = (options?: Partial<Options<AuthPasswordChangeCreateData>>): UseMutationOptions<AuthPasswordChangeCreateResponse, AxiosError<DefaultError>, Options<AuthPasswordChangeCreateData>> => {
    const mutationOptions: UseMutationOptions<AuthPasswordChangeCreateResponse, AxiosError<DefaultError>, Options<AuthPasswordChangeCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authPasswordChangeCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Calls Django Auth PasswordResetForm save method.
 *
 * Accepts the following POST parameters: email
 * Returns the success/fail message.
 */
export const authPasswordResetCreateMutation = (options?: Partial<Options<AuthPasswordResetCreateData>>): UseMutationOptions<AuthPasswordResetCreateResponse, AxiosError<DefaultError>, Options<AuthPasswordResetCreateData>> => {
    const mutationOptions: UseMutationOptions<AuthPasswordResetCreateResponse, AxiosError<DefaultError>, Options<AuthPasswordResetCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authPasswordResetCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Password reset e-mail link is confirmed, therefore
 * this resets the user's password.
 *
 * Accepts the following POST parameters: token, uid,
 * new_password1, new_password2
 * Returns the success/fail message.
 */
export const authPasswordResetConfirmCreateMutation = (options?: Partial<Options<AuthPasswordResetConfirmCreateData>>): UseMutationOptions<AuthPasswordResetConfirmCreateResponse, AxiosError<DefaultError>, Options<AuthPasswordResetConfirmCreateData>> => {
    const mutationOptions: UseMutationOptions<AuthPasswordResetConfirmCreateResponse, AxiosError<DefaultError>, Options<AuthPasswordResetConfirmCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authPasswordResetConfirmCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const authUserRetrieveQueryKey = (options?: Options<AuthUserRetrieveData>) => createQueryKey('authUserRetrieve', options);

/**
 * Reads and updates UserModel fields
 * Accepts GET, PUT, PATCH methods.
 *
 * Default accepted fields: username, first_name, last_name
 * Default display fields: pk, username, email, first_name, last_name
 * Read-only fields: pk, email
 *
 * Returns UserModel fields.
 */
export const authUserRetrieveOptions = (options?: Options<AuthUserRetrieveData>) => queryOptions<AuthUserRetrieveResponse, AxiosError<DefaultError>, AuthUserRetrieveResponse, ReturnType<typeof authUserRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authUserRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authUserRetrieveQueryKey(options)
});

/**
 * Reads and updates UserModel fields
 * Accepts GET, PUT, PATCH methods.
 *
 * Default accepted fields: username, first_name, last_name
 * Default display fields: pk, username, email, first_name, last_name
 * Read-only fields: pk, email
 *
 * Returns UserModel fields.
 */
export const authUserPartialUpdateMutation = (options?: Partial<Options<AuthUserPartialUpdateData>>): UseMutationOptions<AuthUserPartialUpdateResponse, AxiosError<DefaultError>, Options<AuthUserPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<AuthUserPartialUpdateResponse, AxiosError<DefaultError>, Options<AuthUserPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authUserPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reads and updates UserModel fields
 * Accepts GET, PUT, PATCH methods.
 *
 * Default accepted fields: username, first_name, last_name
 * Default display fields: pk, username, email, first_name, last_name
 * Read-only fields: pk, email
 *
 * Returns UserModel fields.
 */
export const authUserUpdateMutation = (options?: Partial<Options<AuthUserUpdateData>>): UseMutationOptions<AuthUserUpdateResponse, AxiosError<DefaultError>, Options<AuthUserUpdateData>> => {
    const mutationOptions: UseMutationOptions<AuthUserUpdateResponse, AxiosError<DefaultError>, Options<AuthUserUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await authUserUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const brandsListQueryKey = (options?: Options<BrandsListData>) => createQueryKey('brandsList', options);

export const brandsListOptions = (options?: Options<BrandsListData>) => queryOptions<BrandsListResponse, AxiosError<DefaultError>, BrandsListResponse, ReturnType<typeof brandsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await brandsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: brandsListQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const brandsListInfiniteQueryKey = (options?: Options<BrandsListData>): QueryKey<Options<BrandsListData>> => createQueryKey('brandsList', options, true);

export const brandsListInfiniteOptions = (options?: Options<BrandsListData>) => {
    const opts = infiniteQueryOptions<BrandsListResponse, AxiosError<DefaultError>, InfiniteData<BrandsListResponse>, QueryKey<Options<BrandsListData>>, number | Pick<QueryKey<Options<BrandsListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<BrandsListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await brandsList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: brandsListInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const brandsCreateMutation = (options?: Partial<Options<BrandsCreateData>>): UseMutationOptions<BrandsCreateResponse, AxiosError<DefaultError>, Options<BrandsCreateData>> => {
    const mutationOptions: UseMutationOptions<BrandsCreateResponse, AxiosError<DefaultError>, Options<BrandsCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await brandsCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const brandsDestroyMutation = (options?: Partial<Options<BrandsDestroyData>>): UseMutationOptions<BrandsDestroyResponse, AxiosError<DefaultError>, Options<BrandsDestroyData>> => {
    const mutationOptions: UseMutationOptions<BrandsDestroyResponse, AxiosError<DefaultError>, Options<BrandsDestroyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await brandsDestroy({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const brandsRetrieveQueryKey = (options: Options<BrandsRetrieveData>) => createQueryKey('brandsRetrieve', options);

export const brandsRetrieveOptions = (options: Options<BrandsRetrieveData>) => queryOptions<BrandsRetrieveResponse, AxiosError<DefaultError>, BrandsRetrieveResponse, ReturnType<typeof brandsRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await brandsRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: brandsRetrieveQueryKey(options)
});

export const brandsPartialUpdateMutation = (options?: Partial<Options<BrandsPartialUpdateData>>): UseMutationOptions<BrandsPartialUpdateResponse, AxiosError<DefaultError>, Options<BrandsPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<BrandsPartialUpdateResponse, AxiosError<DefaultError>, Options<BrandsPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await brandsPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const brandsUpdateMutation = (options?: Partial<Options<BrandsUpdateData>>): UseMutationOptions<BrandsUpdateResponse, AxiosError<DefaultError>, Options<BrandsUpdateData>> => {
    const mutationOptions: UseMutationOptions<BrandsUpdateResponse, AxiosError<DefaultError>, Options<BrandsUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await brandsUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const brandsListAllQueryKey = (options?: Options<BrandsListAllData>) => createQueryKey('brandsListAll', options);

export const brandsListAllOptions = (options?: Options<BrandsListAllData>) => queryOptions<BrandsListAllResponse, AxiosError<DefaultError>, BrandsListAllResponse, ReturnType<typeof brandsListAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await brandsListAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: brandsListAllQueryKey(options)
});

export const categoriesListQueryKey = (options?: Options<CategoriesListData>) => createQueryKey('categoriesList', options);

export const categoriesListOptions = (options?: Options<CategoriesListData>) => queryOptions<CategoriesListResponse, AxiosError<DefaultError>, CategoriesListResponse, ReturnType<typeof categoriesListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await categoriesList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: categoriesListQueryKey(options)
});

export const categoriesListInfiniteQueryKey = (options?: Options<CategoriesListData>): QueryKey<Options<CategoriesListData>> => createQueryKey('categoriesList', options, true);

export const categoriesListInfiniteOptions = (options?: Options<CategoriesListData>) => {
    const opts = infiniteQueryOptions<CategoriesListResponse, AxiosError<DefaultError>, InfiniteData<CategoriesListResponse>, QueryKey<Options<CategoriesListData>>, number | Pick<QueryKey<Options<CategoriesListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<CategoriesListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await categoriesList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: categoriesListInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const categoriesCreateMutation = (options?: Partial<Options<CategoriesCreateData>>): UseMutationOptions<CategoriesCreateResponse, AxiosError<DefaultError>, Options<CategoriesCreateData>> => {
    const mutationOptions: UseMutationOptions<CategoriesCreateResponse, AxiosError<DefaultError>, Options<CategoriesCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await categoriesCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const categoriesDestroyMutation = (options?: Partial<Options<CategoriesDestroyData>>): UseMutationOptions<CategoriesDestroyResponse, AxiosError<DefaultError>, Options<CategoriesDestroyData>> => {
    const mutationOptions: UseMutationOptions<CategoriesDestroyResponse, AxiosError<DefaultError>, Options<CategoriesDestroyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await categoriesDestroy({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const categoriesRetrieveQueryKey = (options: Options<CategoriesRetrieveData>) => createQueryKey('categoriesRetrieve', options);

export const categoriesRetrieveOptions = (options: Options<CategoriesRetrieveData>) => queryOptions<CategoriesRetrieveResponse, AxiosError<DefaultError>, CategoriesRetrieveResponse, ReturnType<typeof categoriesRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await categoriesRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: categoriesRetrieveQueryKey(options)
});

export const categoriesPartialUpdateMutation = (options?: Partial<Options<CategoriesPartialUpdateData>>): UseMutationOptions<CategoriesPartialUpdateResponse, AxiosError<DefaultError>, Options<CategoriesPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<CategoriesPartialUpdateResponse, AxiosError<DefaultError>, Options<CategoriesPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await categoriesPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const categoriesUpdateMutation = (options?: Partial<Options<CategoriesUpdateData>>): UseMutationOptions<CategoriesUpdateResponse, AxiosError<DefaultError>, Options<CategoriesUpdateData>> => {
    const mutationOptions: UseMutationOptions<CategoriesUpdateResponse, AxiosError<DefaultError>, Options<CategoriesUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await categoriesUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const categoriesListAllQueryKey = (options?: Options<CategoriesListAllData>) => createQueryKey('categoriesListAll', options);

export const categoriesListAllOptions = (options?: Options<CategoriesListAllData>) => queryOptions<CategoriesListAllResponse, AxiosError<DefaultError>, CategoriesListAllResponse, ReturnType<typeof categoriesListAllQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await categoriesListAll({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: categoriesListAllQueryKey(options)
});

export const ordersListQueryKey = (options?: Options<OrdersListData>) => createQueryKey('ordersList', options);

export const ordersListOptions = (options?: Options<OrdersListData>) => queryOptions<OrdersListResponse, AxiosError<DefaultError>, OrdersListResponse, ReturnType<typeof ordersListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ordersList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ordersListQueryKey(options)
});

export const ordersListInfiniteQueryKey = (options?: Options<OrdersListData>): QueryKey<Options<OrdersListData>> => createQueryKey('ordersList', options, true);

export const ordersListInfiniteOptions = (options?: Options<OrdersListData>) => {
    const opts = infiniteQueryOptions<OrdersListResponse, AxiosError<DefaultError>, InfiniteData<OrdersListResponse>, QueryKey<Options<OrdersListData>>, number | Pick<QueryKey<Options<OrdersListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<OrdersListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await ordersList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: ordersListInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const ordersCreateMutation = (options?: Partial<Options<OrdersCreateData>>): UseMutationOptions<OrdersCreateResponse, AxiosError<DefaultError>, Options<OrdersCreateData>> => {
    const mutationOptions: UseMutationOptions<OrdersCreateResponse, AxiosError<DefaultError>, Options<OrdersCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersDestroyMutation = (options?: Partial<Options<OrdersDestroyData>>): UseMutationOptions<OrdersDestroyResponse, AxiosError<DefaultError>, Options<OrdersDestroyData>> => {
    const mutationOptions: UseMutationOptions<OrdersDestroyResponse, AxiosError<DefaultError>, Options<OrdersDestroyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersDestroy({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersRetrieveQueryKey = (options: Options<OrdersRetrieveData>) => createQueryKey('ordersRetrieve', options);

export const ordersRetrieveOptions = (options: Options<OrdersRetrieveData>) => queryOptions<OrdersRetrieveResponse, AxiosError<DefaultError>, OrdersRetrieveResponse, ReturnType<typeof ordersRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ordersRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ordersRetrieveQueryKey(options)
});

export const ordersPartialUpdateMutation = (options?: Partial<Options<OrdersPartialUpdateData>>): UseMutationOptions<OrdersPartialUpdateResponse, AxiosError<DefaultError>, Options<OrdersPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<OrdersPartialUpdateResponse, AxiosError<DefaultError>, Options<OrdersPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ordersUpdateMutation = (options?: Partial<Options<OrdersUpdateData>>): UseMutationOptions<OrdersUpdateResponse, AxiosError<DefaultError>, Options<OrdersUpdateData>> => {
    const mutationOptions: UseMutationOptions<OrdersUpdateResponse, AxiosError<DefaultError>, Options<OrdersUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsListQueryKey = (options?: Options<ProductsListData>) => createQueryKey('productsList', options);

export const productsListOptions = (options?: Options<ProductsListData>) => queryOptions<ProductsListResponse, AxiosError<DefaultError>, ProductsListResponse, ReturnType<typeof productsListQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await productsList({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsListQueryKey(options)
});

export const productsListInfiniteQueryKey = (options?: Options<ProductsListData>): QueryKey<Options<ProductsListData>> => createQueryKey('productsList', options, true);

export const productsListInfiniteOptions = (options?: Options<ProductsListData>) => {
    const opts = infiniteQueryOptions<ProductsListResponse, AxiosError<DefaultError>, InfiniteData<ProductsListResponse>, QueryKey<Options<ProductsListData>>, number | Pick<QueryKey<Options<ProductsListData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ProductsListData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await productsList({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: productsListInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const productsCreateMutation = (options?: Partial<Options<ProductsCreateData>>): UseMutationOptions<ProductsCreateResponse, AxiosError<DefaultError>, Options<ProductsCreateData>> => {
    const mutationOptions: UseMutationOptions<ProductsCreateResponse, AxiosError<DefaultError>, Options<ProductsCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsDestroyMutation = (options?: Partial<Options<ProductsDestroyData>>): UseMutationOptions<ProductsDestroyResponse, AxiosError<DefaultError>, Options<ProductsDestroyData>> => {
    const mutationOptions: UseMutationOptions<ProductsDestroyResponse, AxiosError<DefaultError>, Options<ProductsDestroyData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsDestroy({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsRetrieveQueryKey = (options: Options<ProductsRetrieveData>) => createQueryKey('productsRetrieve', options);

export const productsRetrieveOptions = (options: Options<ProductsRetrieveData>) => queryOptions<ProductsRetrieveResponse, AxiosError<DefaultError>, ProductsRetrieveResponse, ReturnType<typeof productsRetrieveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await productsRetrieve({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsRetrieveQueryKey(options)
});

export const productsPartialUpdateMutation = (options?: Partial<Options<ProductsPartialUpdateData>>): UseMutationOptions<ProductsPartialUpdateResponse, AxiosError<DefaultError>, Options<ProductsPartialUpdateData>> => {
    const mutationOptions: UseMutationOptions<ProductsPartialUpdateResponse, AxiosError<DefaultError>, Options<ProductsPartialUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsPartialUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsUpdateMutation = (options?: Partial<Options<ProductsUpdateData>>): UseMutationOptions<ProductsUpdateResponse, AxiosError<DefaultError>, Options<ProductsUpdateData>> => {
    const mutationOptions: UseMutationOptions<ProductsUpdateResponse, AxiosError<DefaultError>, Options<ProductsUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsDetectAndAssignBrandCreateMutation = (options?: Partial<Options<ProductsDetectAndAssignBrandCreateData>>): UseMutationOptions<ProductsDetectAndAssignBrandCreateResponse, AxiosError<DefaultError>, Options<ProductsDetectAndAssignBrandCreateData>> => {
    const mutationOptions: UseMutationOptions<ProductsDetectAndAssignBrandCreateResponse, AxiosError<DefaultError>, Options<ProductsDetectAndAssignBrandCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsDetectAndAssignBrandCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsGenerateSkuCreateMutation = (options?: Partial<Options<ProductsGenerateSkuCreateData>>): UseMutationOptions<ProductsGenerateSkuCreateResponse, AxiosError<DefaultError>, Options<ProductsGenerateSkuCreateData>> => {
    const mutationOptions: UseMutationOptions<ProductsGenerateSkuCreateResponse, AxiosError<DefaultError>, Options<ProductsGenerateSkuCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsGenerateSkuCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
