# Generated by Django 5.2.4 on 2025-07-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_inventory_options_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventories'},
        ),
    ]
